version: '3.9'

services:
  server:
    container_name: golang_container
    network_mode: "host"
    build:
      context: ./server
      dockerfile: Dockerfile
  client:
    container_name: nuxtjs_container
    network_mode: "host"
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server