version: '3.9'

services:
  server:
    container_name: golang_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    network_mode: "host"
  client:
    container_name: nuxtjs_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server