package main

import (
	"encoding/csv"
	"log"
	"os"

	"gorm.io/gorm"
)

type Seeder struct {
	db *gorm.DB
}

func (s Seeder) readFromCSV() {
	f, err := os.Open("data/countries.csv")
	if err != nil {
		log.Fatal(err)
	}

	// remember to close the file at the end of the program
	defer f.Close()

	// read csv values using csv.Reader
	csvReader := csv.NewReader(f)
	data, err := csvReader.ReadAll()
	if err != nil {
		log.Fatal(err)
	}

	for i, line := range data {
		if i > 0 { // omit header line
			var code string
			var name string

			for j, field := range line {
				if j == 0 {
					name = field
				} else if j == 1 {
					code = field
				}
			}
			s.seedCountry(name, code)
		}
	}
}

func (s Seeder) seedCountry(name string, code string) {
	s.db.Create(&Country{Name: name, Code: code})
}

func (s Seeder) SeedCountries() {
	s.readFromCSV()
}
func (s Seeder) seedCountries2() {
	s.db.Create(&Country{Name: "Iran"})
	s.db.Create(&Country{Name: "France"})
	s.db.Create(&Country{Name: "Spain"})
	s.db.Create(&Country{Name: "Afghanistan"})
	s.db.Create(&Country{Name: "Åland Islands"})
	s.db.Create(&Country{Name: "Albania"})
	s.db.Create(&Country{Name: "Algeria"})
	s.db.Create(&Country{Name: "American Samoa"})
	s.db.Create(&Country{Name: "AndorrA"})
	s.db.Create(&Country{Name: "Angola"})
	s.db.Create(&Country{Name: "Anguilla"})
	s.db.Create(&Country{Name: "Antarctica"})
	s.db.Create(&Country{Name: "Antigua and Barbuda"})
	s.db.Create(&Country{Name: "Argentina"})
	s.db.Create(&Country{Name: "Armenia"})
	s.db.Create(&Country{Name: "Aruba"})
	s.db.Create(&Country{Name: "Australia"})
	s.db.Create(&Country{Name: "Austria"})
	s.db.Create(&Country{Name: "Azerbaijan"})
	s.db.Create(&Country{Name: "Bahamas"})
	s.db.Create(&Country{Name: "Bahrain"})
	s.db.Create(&Country{Name: "Bangladesh"})
	s.db.Create(&Country{Name: "Barbados"})
	s.db.Create(&Country{Name: "Belarus"})
	s.db.Create(&Country{Name: "Belgium"})
	s.db.Create(&Country{Name: "Belize"})
	s.db.Create(&Country{Name: "Benin"})
	s.db.Create(&Country{Name: "Bermuda"})
	s.db.Create(&Country{Name: "Bhutan"})
	s.db.Create(&Country{Name: "Bolivia"})
	s.db.Create(&Country{Name: "Bosnia and Herzegovina"})
	s.db.Create(&Country{Name: "Botswana"})
	s.db.Create(&Country{Name: "Bouvet Island"})
	s.db.Create(&Country{Name: "Brazil"})
	s.db.Create(&Country{Name: "British Indian Ocean Territory"})
	s.db.Create(&Country{Name: "Brunei Darussalam"})
	s.db.Create(&Country{Name: "Bulgaria"})
	s.db.Create(&Country{Name: "Burkina Faso"})
	s.db.Create(&Country{Name: "Burundi"})
	s.db.Create(&Country{Name: "Cambodia"})
	s.db.Create(&Country{Name: "Cameroon"})
	s.db.Create(&Country{Name: "Canada"})
	s.db.Create(&Country{Name: "Cape Verde"})
	s.db.Create(&Country{Name: "Cayman Islands"})
	s.db.Create(&Country{Name: "Central African Republic"})
	s.db.Create(&Country{Name: "Chad"})
	s.db.Create(&Country{Name: "Chile"})
	s.db.Create(&Country{Name: "China"})
	s.db.Create(&Country{Name: "Christmas Island"})
	s.db.Create(&Country{Name: "Cocos (Keeling) Islands"})
	s.db.Create(&Country{Name: "Colombia"})
	s.db.Create(&Country{Name: "Comoros"})
	s.db.Create(&Country{Name: "Congo"})
	s.db.Create(&Country{Name: "Congo, The Democratic Republic of the"})
	s.db.Create(&Country{Name: "Cook Islands"})
	s.db.Create(&Country{Name: "Costa Rica"})
	s.db.Create(&Country{Name: "Cote D'Ivoire"})
	s.db.Create(&Country{Name: "Croatia"})
	s.db.Create(&Country{Name: "Cuba"})
	s.db.Create(&Country{Name: "Cyprus"})
	s.db.Create(&Country{Name: "Czech Republic"})
	s.db.Create(&Country{Name: "Denmark"})
	s.db.Create(&Country{Name: "Djibouti"})
	s.db.Create(&Country{Name: "Dominica"})
	s.db.Create(&Country{Name: "Dominican Republic"})
	s.db.Create(&Country{Name: "Ecuador"})
	s.db.Create(&Country{Name: "Egypt"})
	s.db.Create(&Country{Name: "El Salvador"})
	s.db.Create(&Country{Name: "Equatorial Guinea"})
	s.db.Create(&Country{Name: "Eritrea"})
	s.db.Create(&Country{Name: "Estonia"})
	s.db.Create(&Country{Name: "Ethiopia"})
	s.db.Create(&Country{Name: "Falkland Islands (Malvinas)"})
	s.db.Create(&Country{Name: "Faroe Islands"})
	s.db.Create(&Country{Name: "Fiji"})
	s.db.Create(&Country{Name: "Finland"})
	s.db.Create(&Country{Name: "France"})
	s.db.Create(&Country{Name: "French Guiana"})
	s.db.Create(&Country{Name: "French Polynesia"})
	s.db.Create(&Country{Name: "French Southern Territories"})
	s.db.Create(&Country{Name: "Gabon"})
	s.db.Create(&Country{Name: "Gambia"})
	s.db.Create(&Country{Name: "Georgia"})
	s.db.Create(&Country{Name: "Germany"})
	s.db.Create(&Country{Name: "Ghana"})
	s.db.Create(&Country{Name: "Gibraltar"})
	s.db.Create(&Country{Name: "Greece"})
	s.db.Create(&Country{Name: "Greenland"})
	s.db.Create(&Country{Name: "Grenada"})
	s.db.Create(&Country{Name: "Guadeloupe"})
	s.db.Create(&Country{Name: "Guam"})
	s.db.Create(&Country{Name: "Guatemala"})
	s.db.Create(&Country{Name: "Guernsey"})
	s.db.Create(&Country{Name: "Guinea"})
	s.db.Create(&Country{Name: "Guinea-Bissau"})
	s.db.Create(&Country{Name: "Guyana"})
	s.db.Create(&Country{Name: "Haiti"})
	s.db.Create(&Country{Name: "Heard Island and Mcdonald Islands"})
	s.db.Create(&Country{Name: "Holy See (Vatican City State)"})
	s.db.Create(&Country{Name: "Honduras"})
	s.db.Create(&Country{Name: "Hong Kong"})
	s.db.Create(&Country{Name: "Hungary"})
	s.db.Create(&Country{Name: "Iceland"})
	s.db.Create(&Country{Name: "India"})
	s.db.Create(&Country{Name: "Indonesia"})
	s.db.Create(&Country{Name: "Iran, Islamic Republic Of"})
	s.db.Create(&Country{Name: "Iraq"})
	s.db.Create(&Country{Name: "Ireland"})
	s.db.Create(&Country{Name: "Isle of Man"})
	s.db.Create(&Country{Name: "Israel"})
	s.db.Create(&Country{Name: "Italy"})
	s.db.Create(&Country{Name: "Jamaica"})
	s.db.Create(&Country{Name: "Japan"})
	s.db.Create(&Country{Name: "Jersey"})
	s.db.Create(&Country{Name: "Jordan"})
	s.db.Create(&Country{Name: "Kazakhstan"})
	s.db.Create(&Country{Name: "Kenya"})
	s.db.Create(&Country{Name: "Kiribati"})
	s.db.Create(&Country{Name: "Korea, Democratic People'S Republic of"})
	s.db.Create(&Country{Name: "Korea, Republic of"})
	s.db.Create(&Country{Name: "Kuwait"})
	s.db.Create(&Country{Name: "Kyrgyzstan"})
	s.db.Create(&Country{Name: "Lao People's Democratic Republic"})
	s.db.Create(&Country{Name: "Latvia"})
	s.db.Create(&Country{Name: "Lebanon"})
	s.db.Create(&Country{Name: "Lesotho"})
	s.db.Create(&Country{Name: "Liberia"})
	s.db.Create(&Country{Name: "Libyan Arab Jamahiriya"})
	s.db.Create(&Country{Name: "Liechtenstein"})
	s.db.Create(&Country{Name: "Lithuania"})
	s.db.Create(&Country{Name: "Luxembourg"})
	s.db.Create(&Country{Name: "Macao"})
	s.db.Create(&Country{Name: "Macedonia, The Former Yugoslav Republic of"})
	s.db.Create(&Country{Name: "Madagascar"})
	s.db.Create(&Country{Name: "Malawi"})
	s.db.Create(&Country{Name: "Malaysia"})
	s.db.Create(&Country{Name: "Maldives"})
	s.db.Create(&Country{Name: "Mali"})
	s.db.Create(&Country{Name: "Malta"})
	s.db.Create(&Country{Name: "Marshall Islands"})
	s.db.Create(&Country{Name: "Martinique"})
	s.db.Create(&Country{Name: "Mauritania"})
	s.db.Create(&Country{Name: "Mauritius"})
	s.db.Create(&Country{Name: "Mayotte"})
	s.db.Create(&Country{Name: "Mexico"})
	s.db.Create(&Country{Name: "Micronesia, Federated States of"})
	s.db.Create(&Country{Name: "Moldova, Republic of"})
	s.db.Create(&Country{Name: "Monaco"})
	s.db.Create(&Country{Name: "Mongolia"})
	s.db.Create(&Country{Name: "Montserrat"})
	s.db.Create(&Country{Name: "Morocco"})
	s.db.Create(&Country{Name: "Mozambique"})
	s.db.Create(&Country{Name: "Myanmar"})
	s.db.Create(&Country{Name: "Namibia"})
	s.db.Create(&Country{Name: "Nauru"})
	s.db.Create(&Country{Name: "Nepal"})
	s.db.Create(&Country{Name: "Netherlands"})
	s.db.Create(&Country{Name: "Netherlands Antilles"})
	s.db.Create(&Country{Name: "New Caledonia"})
	s.db.Create(&Country{Name: "New Zealand"})
	s.db.Create(&Country{Name: "Nicaragua"})
	s.db.Create(&Country{Name: "Niger"})
	s.db.Create(&Country{Name: "Nigeria"})
	s.db.Create(&Country{Name: "Niue"})
	s.db.Create(&Country{Name: "Norfolk Island"})
	s.db.Create(&Country{Name: "Northern Mariana Islands"})
	s.db.Create(&Country{Name: "Norway"})
	s.db.Create(&Country{Name: "Oman"})
	s.db.Create(&Country{Name: "Pakistan"})
	s.db.Create(&Country{Name: "Palau"})
	s.db.Create(&Country{Name: "Palestinian Territory, Occupied"})
	s.db.Create(&Country{Name: "Panama"})
	s.db.Create(&Country{Name: "Papua New Guinea"})
	s.db.Create(&Country{Name: "Paraguay"})
	s.db.Create(&Country{Name: "Peru"})
	s.db.Create(&Country{Name: "Philippines"})
	s.db.Create(&Country{Name: "Pitcairn"})
	s.db.Create(&Country{Name: "Poland"})
	s.db.Create(&Country{Name: "Portugal"})
	s.db.Create(&Country{Name: "Puerto Rico"})
	s.db.Create(&Country{Name: "Qatar"})
	s.db.Create(&Country{Name: "Reunion"})
	s.db.Create(&Country{Name: "Romania"})
	s.db.Create(&Country{Name: "Russian Federation"})
	s.db.Create(&Country{Name: "RWANDA"})
	s.db.Create(&Country{Name: "Saint Helena"})
	s.db.Create(&Country{Name: "Saint Kitts and Nevis"})
	s.db.Create(&Country{Name: "Saint Lucia"})
	s.db.Create(&Country{Name: "Saint Pierre and Miquelon"})
	s.db.Create(&Country{Name: "Saint Vincent and the Grenadines"})
	s.db.Create(&Country{Name: "Samoa"})
	s.db.Create(&Country{Name: "San Marino"})
	s.db.Create(&Country{Name: "Sao Tome and Principe"})
	s.db.Create(&Country{Name: "Saudi Arabia"})
	s.db.Create(&Country{Name: "Senegal"})
	s.db.Create(&Country{Name: "Serbia and Montenegro"})
	s.db.Create(&Country{Name: "Seychelles"})
	s.db.Create(&Country{Name: "Sierra Leone"})
	s.db.Create(&Country{Name: "Singapore"})
	s.db.Create(&Country{Name: "Slovakia"})
	s.db.Create(&Country{Name: "Slovenia"})
	s.db.Create(&Country{Name: "Solomon Islands"})
	s.db.Create(&Country{Name: "Somalia"})
	s.db.Create(&Country{Name: "South Africa"})
	s.db.Create(&Country{Name: "South Georgia and the South Sandwich Islands"})
	s.db.Create(&Country{Name: "Spain"})
	s.db.Create(&Country{Name: "Sri Lanka"})
	s.db.Create(&Country{Name: "Sudan"})
	s.db.Create(&Country{Name: "Suriname"})
	s.db.Create(&Country{Name: "Svalbard and Jan Mayen"})
	s.db.Create(&Country{Name: "Swaziland"})
	s.db.Create(&Country{Name: "Sweden"})
	s.db.Create(&Country{Name: "Switzerland"})
	s.db.Create(&Country{Name: "Syrian Arab Republic"})
	s.db.Create(&Country{Name: "Taiwan, Province of China"})
	s.db.Create(&Country{Name: "Tajikistan"})
	s.db.Create(&Country{Name: "Tanzania, United Republic of"})
	s.db.Create(&Country{Name: "Thailand"})
	s.db.Create(&Country{Name: "Timor-Leste"})
	s.db.Create(&Country{Name: "Togo"})
	s.db.Create(&Country{Name: "Tokelau"})
	s.db.Create(&Country{Name: "Tonga"})
	s.db.Create(&Country{Name: "Trinidad and Tobago"})
	s.db.Create(&Country{Name: "Tunisia"})
	s.db.Create(&Country{Name: "Turkey"})
	s.db.Create(&Country{Name: "Turkmenistan"})
	s.db.Create(&Country{Name: "Turks and Caicos Islands"})
	s.db.Create(&Country{Name: "Tuvalu"})
	s.db.Create(&Country{Name: "Uganda"})
	s.db.Create(&Country{Name: "Ukraine"})
	s.db.Create(&Country{Name: "United Arab Emirates"})
	s.db.Create(&Country{Name: "United Kingdom"})
	s.db.Create(&Country{Name: "United States"})
	s.db.Create(&Country{Name: "United States Minor Outlying Islands"})
	s.db.Create(&Country{Name: "Uruguay"})
	s.db.Create(&Country{Name: "Uzbekistan"})
	s.db.Create(&Country{Name: "Vanuatu"})
	s.db.Create(&Country{Name: "Venezuela"})
	s.db.Create(&Country{Name: "Viet Nam"})
	s.db.Create(&Country{Name: "Virgin Islands, British"})
	s.db.Create(&Country{Name: "Virgin Islands, U.S."})
	s.db.Create(&Country{Name: "Wallis and Futuna"})
	s.db.Create(&Country{Name: "Western Sahara"})
	s.db.Create(&Country{Name: "Yemen"})
	s.db.Create(&Country{Name: "Zambia"})
	s.db.Create(&Country{Name: "Zimbabwe"})
}
